name: Branch

on:
  pull_request:
    branches: [main]

env:
  HUSKY: 0

jobs:
  branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run Biome
        run: yarn lint
      - name: Run TypeScript
        run: yarn typecheck
      - name: Build application
        run: yarn build
