name: Main

on:
  push:
    branches: [main]

env:
  HUSKY: 0

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: electronuserland/builder:wine
      env:
        ELECTRON_CACHE: /root/.cache/electron
        ELECTRON_BUILDER_CACHE: /root/.cache/electron-builder
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WINEPREFIX: /root/.wine
      volumes:
        - /root/.cache/electron
        - /root/.cache/electron-builder
        - /root/.wine
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run ESLint
        run: yarn lint
      - name: Run TypeScript
        run: yarn typecheck
      - name: Build application
        run: yarn make
