name: Release

on:
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable
      - name: Build application
        run: yarn make
      - name: Get version
        id: get_version
        run: echo "version=v$(npm pkg get version | tr -d '\"')" >> $GITHUB_OUTPUT
      - name: Create tag
        run: |
          version=${{ steps.get_version.outputs.version }}
          git pull
          git tag -a "$version" -m "Version $version"
          git push --follow-tags
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*.exe
          name: Release ${{ steps.get_version.outputs.version }}
          tag: ${{ steps.get_version.outputs.version }}
